version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NAME=your_name_here
  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    environment:
      - NAME=your_name_here
